### ISSUE TITLE
Project Structure Refactoring

### ISSUE THREAD

**Issue by IRWeidman** [mucsci-students/2023sp-420-G-J-IFY#147]
Project Structure Refactoring

Refactor overall project structure and organization

Primary: @IRWeidman, @ybaruti

Secondary: @JMLovegren

Difficulty: Hurt Me Plenty (2)

Actual Difficulty: 3

Actual Time: 2 hours and a lot of stress

**Comment by JMLovegren** [comment]
@IRWeidman be sure to update actual difficulty and actual time
