### ISSUE TITLE
Loading: Loading another team's file results in a missing entered word

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-G-J-IFY#230]

**Comment by JMLovegren** [comment]
So, there’s 2 different things here that I’ll address one at a time. 

1. We made the decision to implement a save game checker function. This does things like make sure that the game coming in has the same max score and word list as we would expect, as well as making sure that guessed words are valid to the game and scored correctly . In our testing, this worked really well to ensure that we had the correct words in the game and our software would function as intended even when working with foreign data. There is a small chance that this is the situation you ran into. 

2. We discovered while debugging this issue that this was happening with a specific team’s saves (MediaTek). After talking to them yesterday, they’re violating the save standard, and removing words from the valid word list after they’ve been guessed. This then destroyed the logic of our checker, and likely led to the removed words you discovered when you filed this issue. 

Do you know what team’s save it was that caused this issue?

**Comment by JMLovegren** [comment]
Dig it. I’ll work through this
