### ISSUE TITLE
GUI: The status bar is not cleared after starting a new game

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-G-J-IFY#233]

**Comment by JMLovegren** [comment]
Assigned to @IRWeidman

**Comment by willkill07** [comment]
macOS

**Comment by willkill07** [comment]
It may not repro now, but try it with the sprint 2 release?

0. be on macOS.
1. Play a game where the status bar is updated.
2. Start a new game.
3. Observe that the status bar was not cleared.
