### ISSUE TITLE
Tab Autocomplete

### ISSUE THREAD

**Issue by ybaruti** [mucsci-students/2023sp-420-G-J-IFY#247]
Tab Autocomplete

When inputting ! have the ability to hit tab and autocomplete a selected command

Primary: @Frannyspag24 

Secondary: @IRWeidman 

Size: Ultra Violence

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by JMLovegren** [comment]
Task was not completed for sprint 3 and is added to technical debt
