### ISSUE TITLE
Continous Intergration on Github

### ISSUE THREAD

**Issue by ybaruti** [mucsci-students/2023sp-420-G-J-IFY#250]
Continous Intergration on Github

Implement GitHub actions and automatically running tests when trying to initiate pull requests

Primary: @jmlovegren

Secondary: @gmzakros

Size: Ultra Nightmare

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by JMLovegren** [comment]
Just running the tests is working fine, but there's a lot of other actions we could/should be doing that were a nightmare to figure out. I could not get it to properly build on the windows VM, so we're only testing on Linux/Mac.

But, pytest is up and running, and its working for new PRs
